#!/bin/bash

# Install a JupyterLab extension for demonstration purposes
git clone https://git.savannah.nongnu.org/git/getfem.git
cd getfem
bash autogen.sh
./configure --with-pic --enable-python3=yes
make -j8 check
